apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minecraft.fullname" . }}-jvm
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
data:
  user_jvm_args.txt: |
    {{- include "minecraft.userJvmArgs" . | nindent 4 }}
