apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}-headless
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
  ports:
    - name: minecraft
      port: {{ .Values.minecraft.servicePort }}
      targetPort: minecraft
