apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.externalDNS.enabled }}
  annotations:
    {{- if .Values.externalDNS.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDNS.hostname | quote }}
    external-dns.alpha.kubernetes.io/ttl: {{ .Values.externalDNS.ttl | quote }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: {{ .Values.externalDNS.proxied | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
  ports:
    - name: minecraft-tcp
      port: {{ .Values.minecraft.servicePort }}
      targetPort: {{ .Values.minecraft.servicePort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: minecraft-udp
      port: {{ .Values.minecraft.servicePort }}
      targetPort: {{ .Values.minecraft.servicePort }}
      protocol: UDP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
